branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - 'main'
  - 'next'
  - 'next-major'
  
  - name: 'beta'
    prerelease: true
  
  - name: 'alpha'
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
      - "dist/**/*.*"
  - - "@semantic-release/npm"
    - npmPublish: true
  - - "@semantic-release/changelog"
    - assets:
      - CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - package.json
      - package-lock.json
