name: Release
on:
  push:
    branches:
      - main

jobs:
  semantic_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm

      - name: Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.4.2
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}